# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mongrol/dev/scorch/tractionedge

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mongrol/dev/scorch/tractionedge

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mongrol/dev/scorch/tractionedge/CMakeFiles /home/mongrol/dev/scorch/tractionedge/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mongrol/dev/scorch/tractionedge/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tractionedge

# Build rule for target.
tractionedge: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tractionedge
.PHONY : tractionedge

# fast build rule for target.
tractionedge/fast:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/build
.PHONY : tractionedge/fast

AnimManager.o: AnimManager.cpp.o
.PHONY : AnimManager.o

# target to build an object file
AnimManager.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/AnimManager.cpp.o
.PHONY : AnimManager.cpp.o

AnimManager.i: AnimManager.cpp.i
.PHONY : AnimManager.i

# target to preprocess a source file
AnimManager.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/AnimManager.cpp.i
.PHONY : AnimManager.cpp.i

AnimManager.s: AnimManager.cpp.s
.PHONY : AnimManager.s

# target to generate assembly for a file
AnimManager.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/AnimManager.cpp.s
.PHONY : AnimManager.cpp.s

Creature.o: Creature.cpp.o
.PHONY : Creature.o

# target to build an object file
Creature.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/Creature.cpp.o
.PHONY : Creature.cpp.o

Creature.i: Creature.cpp.i
.PHONY : Creature.i

# target to preprocess a source file
Creature.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/Creature.cpp.i
.PHONY : Creature.cpp.i

Creature.s: Creature.cpp.s
.PHONY : Creature.s

# target to generate assembly for a file
Creature.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/Creature.cpp.s
.PHONY : Creature.cpp.s

DisplayManager.o: DisplayManager.cpp.o
.PHONY : DisplayManager.o

# target to build an object file
DisplayManager.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/DisplayManager.cpp.o
.PHONY : DisplayManager.cpp.o

DisplayManager.i: DisplayManager.cpp.i
.PHONY : DisplayManager.i

# target to preprocess a source file
DisplayManager.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/DisplayManager.cpp.i
.PHONY : DisplayManager.cpp.i

DisplayManager.s: DisplayManager.cpp.s
.PHONY : DisplayManager.s

# target to generate assembly for a file
DisplayManager.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/DisplayManager.cpp.s
.PHONY : DisplayManager.cpp.s

Engine.o: Engine.cpp.o
.PHONY : Engine.o

# target to build an object file
Engine.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/Engine.cpp.o
.PHONY : Engine.cpp.o

Engine.i: Engine.cpp.i
.PHONY : Engine.i

# target to preprocess a source file
Engine.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/Engine.cpp.i
.PHONY : Engine.cpp.i

Engine.s: Engine.cpp.s
.PHONY : Engine.s

# target to generate assembly for a file
Engine.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/Engine.cpp.s
.PHONY : Engine.cpp.s

EngineState.o: EngineState.cpp.o
.PHONY : EngineState.o

# target to build an object file
EngineState.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/EngineState.cpp.o
.PHONY : EngineState.cpp.o

EngineState.i: EngineState.cpp.i
.PHONY : EngineState.i

# target to preprocess a source file
EngineState.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/EngineState.cpp.i
.PHONY : EngineState.cpp.i

EngineState.s: EngineState.cpp.s
.PHONY : EngineState.s

# target to generate assembly for a file
EngineState.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/EngineState.cpp.s
.PHONY : EngineState.cpp.s

FSM.o: FSM.cpp.o
.PHONY : FSM.o

# target to build an object file
FSM.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/FSM.cpp.o
.PHONY : FSM.cpp.o

FSM.i: FSM.cpp.i
.PHONY : FSM.i

# target to preprocess a source file
FSM.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/FSM.cpp.i
.PHONY : FSM.cpp.i

FSM.s: FSM.cpp.s
.PHONY : FSM.s

# target to generate assembly for a file
FSM.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/FSM.cpp.s
.PHONY : FSM.cpp.s

FSMState.o: FSMState.cpp.o
.PHONY : FSMState.o

# target to build an object file
FSMState.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/FSMState.cpp.o
.PHONY : FSMState.cpp.o

FSMState.i: FSMState.cpp.i
.PHONY : FSMState.i

# target to preprocess a source file
FSMState.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/FSMState.cpp.i
.PHONY : FSMState.cpp.i

FSMState.s: FSMState.cpp.s
.PHONY : FSMState.s

# target to generate assembly for a file
FSMState.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/FSMState.cpp.s
.PHONY : FSMState.cpp.s

GameWorld.o: GameWorld.cpp.o
.PHONY : GameWorld.o

# target to build an object file
GameWorld.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/GameWorld.cpp.o
.PHONY : GameWorld.cpp.o

GameWorld.i: GameWorld.cpp.i
.PHONY : GameWorld.i

# target to preprocess a source file
GameWorld.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/GameWorld.cpp.i
.PHONY : GameWorld.cpp.i

GameWorld.s: GameWorld.cpp.s
.PHONY : GameWorld.s

# target to generate assembly for a file
GameWorld.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/GameWorld.cpp.s
.PHONY : GameWorld.cpp.s

GfxSFML.o: GfxSFML.cpp.o
.PHONY : GfxSFML.o

# target to build an object file
GfxSFML.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/GfxSFML.cpp.o
.PHONY : GfxSFML.cpp.o

GfxSFML.i: GfxSFML.cpp.i
.PHONY : GfxSFML.i

# target to preprocess a source file
GfxSFML.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/GfxSFML.cpp.i
.PHONY : GfxSFML.cpp.i

GfxSFML.s: GfxSFML.cpp.s
.PHONY : GfxSFML.s

# target to generate assembly for a file
GfxSFML.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/GfxSFML.cpp.s
.PHONY : GfxSFML.cpp.s

Item.o: Item.cpp.o
.PHONY : Item.o

# target to build an object file
Item.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/Item.cpp.o
.PHONY : Item.cpp.o

Item.i: Item.cpp.i
.PHONY : Item.i

# target to preprocess a source file
Item.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/Item.cpp.i
.PHONY : Item.cpp.i

Item.s: Item.cpp.s
.PHONY : Item.s

# target to generate assembly for a file
Item.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/Item.cpp.s
.PHONY : Item.cpp.s

Map.o: Map.cpp.o
.PHONY : Map.o

# target to build an object file
Map.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/Map.cpp.o
.PHONY : Map.cpp.o

Map.i: Map.cpp.i
.PHONY : Map.i

# target to preprocess a source file
Map.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/Map.cpp.i
.PHONY : Map.cpp.i

Map.s: Map.cpp.s
.PHONY : Map.s

# target to generate assembly for a file
Map.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/Map.cpp.s
.PHONY : Map.cpp.s

MapGenerator.o: MapGenerator.cpp.o
.PHONY : MapGenerator.o

# target to build an object file
MapGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/MapGenerator.cpp.o
.PHONY : MapGenerator.cpp.o

MapGenerator.i: MapGenerator.cpp.i
.PHONY : MapGenerator.i

# target to preprocess a source file
MapGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/MapGenerator.cpp.i
.PHONY : MapGenerator.cpp.i

MapGenerator.s: MapGenerator.cpp.s
.PHONY : MapGenerator.s

# target to generate assembly for a file
MapGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/MapGenerator.cpp.s
.PHONY : MapGenerator.cpp.s

NameGenerator.o: NameGenerator.cpp.o
.PHONY : NameGenerator.o

# target to build an object file
NameGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/NameGenerator.cpp.o
.PHONY : NameGenerator.cpp.o

NameGenerator.i: NameGenerator.cpp.i
.PHONY : NameGenerator.i

# target to preprocess a source file
NameGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/NameGenerator.cpp.i
.PHONY : NameGenerator.cpp.i

NameGenerator.s: NameGenerator.cpp.s
.PHONY : NameGenerator.s

# target to generate assembly for a file
NameGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/NameGenerator.cpp.s
.PHONY : NameGenerator.cpp.s

Position.o: Position.cpp.o
.PHONY : Position.o

# target to build an object file
Position.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/Position.cpp.o
.PHONY : Position.cpp.o

Position.i: Position.cpp.i
.PHONY : Position.i

# target to preprocess a source file
Position.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/Position.cpp.i
.PHONY : Position.cpp.i

Position.s: Position.cpp.s
.PHONY : Position.s

# target to generate assembly for a file
Position.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/Position.cpp.s
.PHONY : Position.cpp.s

Saver.o: Saver.cpp.o
.PHONY : Saver.o

# target to build an object file
Saver.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/Saver.cpp.o
.PHONY : Saver.cpp.o

Saver.i: Saver.cpp.i
.PHONY : Saver.i

# target to preprocess a source file
Saver.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/Saver.cpp.i
.PHONY : Saver.cpp.i

Saver.s: Saver.cpp.s
.PHONY : Saver.s

# target to generate assembly for a file
Saver.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/Saver.cpp.s
.PHONY : Saver.cpp.s

SquadAI.o: SquadAI.cpp.o
.PHONY : SquadAI.o

# target to build an object file
SquadAI.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/SquadAI.cpp.o
.PHONY : SquadAI.cpp.o

SquadAI.i: SquadAI.cpp.i
.PHONY : SquadAI.i

# target to preprocess a source file
SquadAI.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/SquadAI.cpp.i
.PHONY : SquadAI.cpp.i

SquadAI.s: SquadAI.cpp.s
.PHONY : SquadAI.s

# target to generate assembly for a file
SquadAI.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/SquadAI.cpp.s
.PHONY : SquadAI.cpp.s

Terrain.o: Terrain.cpp.o
.PHONY : Terrain.o

# target to build an object file
Terrain.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/Terrain.cpp.o
.PHONY : Terrain.cpp.o

Terrain.i: Terrain.cpp.i
.PHONY : Terrain.i

# target to preprocess a source file
Terrain.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/Terrain.cpp.i
.PHONY : Terrain.cpp.i

Terrain.s: Terrain.cpp.s
.PHONY : Terrain.s

# target to generate assembly for a file
Terrain.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/Terrain.cpp.s
.PHONY : Terrain.cpp.s

UIEmbarkScreen.o: UIEmbarkScreen.cpp.o
.PHONY : UIEmbarkScreen.o

# target to build an object file
UIEmbarkScreen.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/UIEmbarkScreen.cpp.o
.PHONY : UIEmbarkScreen.cpp.o

UIEmbarkScreen.i: UIEmbarkScreen.cpp.i
.PHONY : UIEmbarkScreen.i

# target to preprocess a source file
UIEmbarkScreen.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/UIEmbarkScreen.cpp.i
.PHONY : UIEmbarkScreen.cpp.i

UIEmbarkScreen.s: UIEmbarkScreen.cpp.s
.PHONY : UIEmbarkScreen.s

# target to generate assembly for a file
UIEmbarkScreen.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/UIEmbarkScreen.cpp.s
.PHONY : UIEmbarkScreen.cpp.s

UIGameOverScreen.o: UIGameOverScreen.cpp.o
.PHONY : UIGameOverScreen.o

# target to build an object file
UIGameOverScreen.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/UIGameOverScreen.cpp.o
.PHONY : UIGameOverScreen.cpp.o

UIGameOverScreen.i: UIGameOverScreen.cpp.i
.PHONY : UIGameOverScreen.i

# target to preprocess a source file
UIGameOverScreen.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/UIGameOverScreen.cpp.i
.PHONY : UIGameOverScreen.cpp.i

UIGameOverScreen.s: UIGameOverScreen.cpp.s
.PHONY : UIGameOverScreen.s

# target to generate assembly for a file
UIGameOverScreen.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/UIGameOverScreen.cpp.s
.PHONY : UIGameOverScreen.cpp.s

UIIntroScreen.o: UIIntroScreen.cpp.o
.PHONY : UIIntroScreen.o

# target to build an object file
UIIntroScreen.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/UIIntroScreen.cpp.o
.PHONY : UIIntroScreen.cpp.o

UIIntroScreen.i: UIIntroScreen.cpp.i
.PHONY : UIIntroScreen.i

# target to preprocess a source file
UIIntroScreen.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/UIIntroScreen.cpp.i
.PHONY : UIIntroScreen.cpp.i

UIIntroScreen.s: UIIntroScreen.cpp.s
.PHONY : UIIntroScreen.s

# target to generate assembly for a file
UIIntroScreen.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/UIIntroScreen.cpp.s
.PHONY : UIIntroScreen.cpp.s

UIMatchScreen.o: UIMatchScreen.cpp.o
.PHONY : UIMatchScreen.o

# target to build an object file
UIMatchScreen.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/UIMatchScreen.cpp.o
.PHONY : UIMatchScreen.cpp.o

UIMatchScreen.i: UIMatchScreen.cpp.i
.PHONY : UIMatchScreen.i

# target to preprocess a source file
UIMatchScreen.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/UIMatchScreen.cpp.i
.PHONY : UIMatchScreen.cpp.i

UIMatchScreen.s: UIMatchScreen.cpp.s
.PHONY : UIMatchScreen.s

# target to generate assembly for a file
UIMatchScreen.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/UIMatchScreen.cpp.s
.PHONY : UIMatchScreen.cpp.s

UIOptionsScreen.o: UIOptionsScreen.cpp.o
.PHONY : UIOptionsScreen.o

# target to build an object file
UIOptionsScreen.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/UIOptionsScreen.cpp.o
.PHONY : UIOptionsScreen.cpp.o

UIOptionsScreen.i: UIOptionsScreen.cpp.i
.PHONY : UIOptionsScreen.i

# target to preprocess a source file
UIOptionsScreen.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/UIOptionsScreen.cpp.i
.PHONY : UIOptionsScreen.cpp.i

UIOptionsScreen.s: UIOptionsScreen.cpp.s
.PHONY : UIOptionsScreen.s

# target to generate assembly for a file
UIOptionsScreen.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/UIOptionsScreen.cpp.s
.PHONY : UIOptionsScreen.cpp.s

UIResultsScreen.o: UIResultsScreen.cpp.o
.PHONY : UIResultsScreen.o

# target to build an object file
UIResultsScreen.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/UIResultsScreen.cpp.o
.PHONY : UIResultsScreen.cpp.o

UIResultsScreen.i: UIResultsScreen.cpp.i
.PHONY : UIResultsScreen.i

# target to preprocess a source file
UIResultsScreen.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/UIResultsScreen.cpp.i
.PHONY : UIResultsScreen.cpp.i

UIResultsScreen.s: UIResultsScreen.cpp.s
.PHONY : UIResultsScreen.s

# target to generate assembly for a file
UIResultsScreen.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/UIResultsScreen.cpp.s
.PHONY : UIResultsScreen.cpp.s

UITitleScreen.o: UITitleScreen.cpp.o
.PHONY : UITitleScreen.o

# target to build an object file
UITitleScreen.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/UITitleScreen.cpp.o
.PHONY : UITitleScreen.cpp.o

UITitleScreen.i: UITitleScreen.cpp.i
.PHONY : UITitleScreen.i

# target to preprocess a source file
UITitleScreen.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/UITitleScreen.cpp.i
.PHONY : UITitleScreen.cpp.i

UITitleScreen.s: UITitleScreen.cpp.s
.PHONY : UITitleScreen.s

# target to generate assembly for a file
UITitleScreen.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/UITitleScreen.cpp.s
.PHONY : UITitleScreen.cpp.s

UIView.o: UIView.cpp.o
.PHONY : UIView.o

# target to build an object file
UIView.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/UIView.cpp.o
.PHONY : UIView.cpp.o

UIView.i: UIView.cpp.i
.PHONY : UIView.i

# target to preprocess a source file
UIView.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/UIView.cpp.i
.PHONY : UIView.cpp.i

UIView.s: UIView.cpp.s
.PHONY : UIView.s

# target to generate assembly for a file
UIView.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/UIView.cpp.s
.PHONY : UIView.cpp.s

Utility.o: Utility.cpp.o
.PHONY : Utility.o

# target to build an object file
Utility.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/Utility.cpp.o
.PHONY : Utility.cpp.o

Utility.i: Utility.cpp.i
.PHONY : Utility.i

# target to preprocess a source file
Utility.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/Utility.cpp.i
.PHONY : Utility.cpp.i

Utility.s: Utility.cpp.s
.PHONY : Utility.s

# target to generate assembly for a file
Utility.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/Utility.cpp.s
.PHONY : Utility.cpp.s

blah.o: blah.cpp.o
.PHONY : blah.o

# target to build an object file
blah.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/blah.cpp.o
.PHONY : blah.cpp.o

blah.i: blah.cpp.i
.PHONY : blah.i

# target to preprocess a source file
blah.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/blah.cpp.i
.PHONY : blah.cpp.i

blah.s: blah.cpp.s
.PHONY : blah.s

# target to generate assembly for a file
blah.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/blah.cpp.s
.PHONY : blah.cpp.s

fov.o: fov.cpp.o
.PHONY : fov.o

# target to build an object file
fov.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/fov.cpp.o
.PHONY : fov.cpp.o

fov.i: fov.cpp.i
.PHONY : fov.i

# target to preprocess a source file
fov.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/fov.cpp.i
.PHONY : fov.cpp.i

fov.s: fov.cpp.s
.PHONY : fov.s

# target to generate assembly for a file
fov.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/fov.cpp.s
.PHONY : fov.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/main.cpp.s
.PHONY : main.cpp.s

tinystr.o: tinystr.cpp.o
.PHONY : tinystr.o

# target to build an object file
tinystr.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/tinystr.cpp.o
.PHONY : tinystr.cpp.o

tinystr.i: tinystr.cpp.i
.PHONY : tinystr.i

# target to preprocess a source file
tinystr.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/tinystr.cpp.i
.PHONY : tinystr.cpp.i

tinystr.s: tinystr.cpp.s
.PHONY : tinystr.s

# target to generate assembly for a file
tinystr.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/tinystr.cpp.s
.PHONY : tinystr.cpp.s

tinyxml.o: tinyxml.cpp.o
.PHONY : tinyxml.o

# target to build an object file
tinyxml.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/tinyxml.cpp.o
.PHONY : tinyxml.cpp.o

tinyxml.i: tinyxml.cpp.i
.PHONY : tinyxml.i

# target to preprocess a source file
tinyxml.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/tinyxml.cpp.i
.PHONY : tinyxml.cpp.i

tinyxml.s: tinyxml.cpp.s
.PHONY : tinyxml.s

# target to generate assembly for a file
tinyxml.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/tinyxml.cpp.s
.PHONY : tinyxml.cpp.s

tinyxmlerror.o: tinyxmlerror.cpp.o
.PHONY : tinyxmlerror.o

# target to build an object file
tinyxmlerror.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/tinyxmlerror.cpp.o
.PHONY : tinyxmlerror.cpp.o

tinyxmlerror.i: tinyxmlerror.cpp.i
.PHONY : tinyxmlerror.i

# target to preprocess a source file
tinyxmlerror.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/tinyxmlerror.cpp.i
.PHONY : tinyxmlerror.cpp.i

tinyxmlerror.s: tinyxmlerror.cpp.s
.PHONY : tinyxmlerror.s

# target to generate assembly for a file
tinyxmlerror.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/tinyxmlerror.cpp.s
.PHONY : tinyxmlerror.cpp.s

tinyxmlparser.o: tinyxmlparser.cpp.o
.PHONY : tinyxmlparser.o

# target to build an object file
tinyxmlparser.cpp.o:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/tinyxmlparser.cpp.o
.PHONY : tinyxmlparser.cpp.o

tinyxmlparser.i: tinyxmlparser.cpp.i
.PHONY : tinyxmlparser.i

# target to preprocess a source file
tinyxmlparser.cpp.i:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/tinyxmlparser.cpp.i
.PHONY : tinyxmlparser.cpp.i

tinyxmlparser.s: tinyxmlparser.cpp.s
.PHONY : tinyxmlparser.s

# target to generate assembly for a file
tinyxmlparser.cpp.s:
	$(MAKE) -f CMakeFiles/tractionedge.dir/build.make CMakeFiles/tractionedge.dir/tinyxmlparser.cpp.s
.PHONY : tinyxmlparser.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tractionedge"
	@echo "... AnimManager.o"
	@echo "... AnimManager.i"
	@echo "... AnimManager.s"
	@echo "... Creature.o"
	@echo "... Creature.i"
	@echo "... Creature.s"
	@echo "... DisplayManager.o"
	@echo "... DisplayManager.i"
	@echo "... DisplayManager.s"
	@echo "... Engine.o"
	@echo "... Engine.i"
	@echo "... Engine.s"
	@echo "... EngineState.o"
	@echo "... EngineState.i"
	@echo "... EngineState.s"
	@echo "... FSM.o"
	@echo "... FSM.i"
	@echo "... FSM.s"
	@echo "... FSMState.o"
	@echo "... FSMState.i"
	@echo "... FSMState.s"
	@echo "... GameWorld.o"
	@echo "... GameWorld.i"
	@echo "... GameWorld.s"
	@echo "... GfxSFML.o"
	@echo "... GfxSFML.i"
	@echo "... GfxSFML.s"
	@echo "... Item.o"
	@echo "... Item.i"
	@echo "... Item.s"
	@echo "... Map.o"
	@echo "... Map.i"
	@echo "... Map.s"
	@echo "... MapGenerator.o"
	@echo "... MapGenerator.i"
	@echo "... MapGenerator.s"
	@echo "... NameGenerator.o"
	@echo "... NameGenerator.i"
	@echo "... NameGenerator.s"
	@echo "... Position.o"
	@echo "... Position.i"
	@echo "... Position.s"
	@echo "... Saver.o"
	@echo "... Saver.i"
	@echo "... Saver.s"
	@echo "... SquadAI.o"
	@echo "... SquadAI.i"
	@echo "... SquadAI.s"
	@echo "... Terrain.o"
	@echo "... Terrain.i"
	@echo "... Terrain.s"
	@echo "... UIEmbarkScreen.o"
	@echo "... UIEmbarkScreen.i"
	@echo "... UIEmbarkScreen.s"
	@echo "... UIGameOverScreen.o"
	@echo "... UIGameOverScreen.i"
	@echo "... UIGameOverScreen.s"
	@echo "... UIIntroScreen.o"
	@echo "... UIIntroScreen.i"
	@echo "... UIIntroScreen.s"
	@echo "... UIMatchScreen.o"
	@echo "... UIMatchScreen.i"
	@echo "... UIMatchScreen.s"
	@echo "... UIOptionsScreen.o"
	@echo "... UIOptionsScreen.i"
	@echo "... UIOptionsScreen.s"
	@echo "... UIResultsScreen.o"
	@echo "... UIResultsScreen.i"
	@echo "... UIResultsScreen.s"
	@echo "... UITitleScreen.o"
	@echo "... UITitleScreen.i"
	@echo "... UITitleScreen.s"
	@echo "... UIView.o"
	@echo "... UIView.i"
	@echo "... UIView.s"
	@echo "... Utility.o"
	@echo "... Utility.i"
	@echo "... Utility.s"
	@echo "... blah.o"
	@echo "... blah.i"
	@echo "... blah.s"
	@echo "... fov.o"
	@echo "... fov.i"
	@echo "... fov.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... tinystr.o"
	@echo "... tinystr.i"
	@echo "... tinystr.s"
	@echo "... tinyxml.o"
	@echo "... tinyxml.i"
	@echo "... tinyxml.s"
	@echo "... tinyxmlerror.o"
	@echo "... tinyxmlerror.i"
	@echo "... tinyxmlerror.s"
	@echo "... tinyxmlparser.o"
	@echo "... tinyxmlparser.i"
	@echo "... tinyxmlparser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

